run-1:
	go run main.go -name=srv1 -bind-port=9001

run-2:
	go run main.go -name=srv2 -bind-port=9002 -join-addresses=127.0.0.1:9001

run-3:
	go run main.go -name=srv3 -bind-port=9003 -join-addresses=127.0.0.1:9001